version: '3.8'

services:
  api:
    build: .
    container_name: selenium-pdf-api
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
    volumes:
      - ./pdfs:/app/pdfs
      - ./downloads:/app/downloads
    networks:
      - traefik_network
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.doc2md.rule=Host(`pdf.sosprecatorios.site`)
        - traefik.http.routers.doc2md.entrypoints=websecure
        - traefik.http.routers.doc2md.tls.certresolver=letsencryptresolver
        - traefik.http.routers.doc2md.priority=1
        - traefik.http.routers.doc2md.service=doc2md
        - traefik.http.services.doc2md.loadbalancer.server.port=5001
        - traefik.http.services.doc2md.loadbalancer.passHostHeader=true

networks:
  traefik_network:
    external: true 