version: '3.8'

services:
  api:
    build: .
    container_name: selenium-pdf-api
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
    volumes:
      - ./pdfs:/app/pdfs
      - ./downloads:/app/downloads
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.selenium-pdf.rule=Host(`api.seu-dominio.com`)"
      - "traefik.http.routers.selenium-pdf.entrypoints=websecure"
      - "traefik.http.routers.selenium-pdf.tls.certresolver=letsencrypt"
      - "traefik.http.services.selenium-pdf.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik_network"

networks:
  traefik_network:
    external: true 