version: '3.8'

services:
  pje-scraper:
    build: .
    container_name: pje-scraper-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=api_server.py
      - USER=${USER:-seu_usuario_pje}
      - PASSWORD=${PASSWORD:-sua_senha_pje}
      - API_URL=http://localhost:5000/upload
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=False
    volumes:
      - pdfs_data:/app/pdfs
      - downloads_data:/app/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pje-network

volumes:
  pdfs_data:
    driver: local
  downloads_data:
    driver: local

networks:
  pje-network:
    driver: bridge 