version: '3.8'

services:
  pje-scraper:
    build: .
    container_name: pje-scraper
    ports:
      - "5001:5001"
    volumes:
      # Volume para desktop (detectado automaticamente)
      - "C:/Users/gabri/OneDrive/Attachments/Área de Trabalho:/app/desktop:rw"
      # Volume para downloads (fallback)
      - ./downloads:/app/downloads
      # Volume para configurações (opcional)
      - ./.env:/app/.env
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Configurações de recursos
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    # Configurações de segurança
    security_opt:
      - seccomp:unconfined
    # Configurações de rede
    networks:
      - pje-network

networks:
  pje-network:
    driver: bridge

volumes:
  downloads:
    driver: local
